### ISSUE TITLE
DOMException on "fast" forward in browser history

### ISSUE THREAD

**Issue by aloupfor** [vuestorefront/vue-storefront#4537]
## Current behavior
Browsing using browser history cause page to not load properly.

## Expected behavior
Browsing using browser history cause page to load properly.

## Steps to reproduce the issue
Open a new blank browser tab.
Go to https://demo.vuestorefront.io/.
Click to go to https://demo.vuestorefront.io/women.html.
Click back in browser history to go to https://demo.vuestorefront.io/.
Click back in browser history to go to blank browser tab.
Double-click on forward browser history (or ALT + Left twice "fast") to go to https://demo.vuestorefront.io/women.html.
Page does not load properly.

![Screenshot from 2020-06-11 19-21-48](https://user-images.githubusercontent.com/11750180/84419402-d6bb1980-ac18-11ea-9516-dcba5a372c1a.png)

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Chromium Version 73.0.3683.75
* OS: Debian 9

## Additional information
```
vue.runtime.esm.js:1888 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:40559)
    at h (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:53291)
    at l (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:53028)
    at d (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:53377)
    at E (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:56715)
    at E (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:56650)
    at a.__patch__ (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:57115)
    at a.t._update (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:34351)
    at a.n (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:64431)
    at lr.get (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:7:26610)
```

Might be the same error than https://github.com/DivanteLtd/vue-storefront/issues/3669.

**Comment by Fifciu** [comment]
This is the nature of how SPA works. We can do nothing if someone prevent from loading essential resources in the middle.
