### ISSUE TITLE
TypeError: Cannot read property 'attribute_id' of null

### ISSUE THREAD

**Issue by kuldeepkiwitech** [vuestorefront/vue-storefront#4779]
## Current behavior
error: Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'attribute_id' of null
      at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/produc
t.js:256:47)
      at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37
      at Array.map (<anonymous>)
      at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js
:260:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: 
{
  message: "Cannot read property 'attribute_id' of null",
  stack: "TypeError: Cannot read property 'attribute_id' of null\n" +
    '    at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/pro
duct.js:256:47)\n' +
    '    at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37\n' 

* 

```
'    at Array.map (<anonymous>)\n' +
'    at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product
```

.js:260:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}

## Expected behavior
It should import products

## Steps to reproduce the issue
Run yarn mage2vs import it happens sometime and sometime it works

## Version of Vue Storefront

* [ ] Vue Storefront -- ## [1.12.3] 

## Can you handle fixing this bug by yourself?
* [x] NO

## Environment details

* Browser: NA
* OS: Linux
* Node: 12.18.3
* Code Version: [1.12.3]

**Comment by himanshutecstub** [comment]
I fetch same issue during installation with latest version any solution?

**Comment by agilepartnerantoine** [comment]
Same issue when I want to install vue storefront with yarn run installer

```
[34mdebug[39m: Response received.

2021-02-11T13:05:57.154Z - [32minfo[39m: Configurable options for vue_storefront_catalog_attr_203
2021-02-11T13:05:57.155Z - [32minfo[39m: Configurable options expanded!

2021-02-11T13:05:57.160Z - [31merror[39m: Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'attribute_id' of null
      at findOptionValues (/var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:256:47)
      at /var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37
      at Array.map (<anonymous>)
      at selectFields (/var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:260:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: 
{
  message: [32m"Cannot read property 'attribute_id' of null"[39m,
  stack: [32m"TypeError: Cannot read property 'attribute_id' of null\n"[39m +
    [32m'    at findOptionValues (/var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:256:47)\n'[39m +
    [32m'    at /var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37\n'[39m +
    [32m'    at Array.map (<anonymous>)\n'[39m +
    [32m'    at selectFields (/var/www/html/vuestorefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:260:39)\n'[39m +
    [32m'    at runMicrotasks (<anonymous>)\n'[39m +
    [32m'    at processTicksAndRejections (internal/process/task_queues.js:97:5)'[39m
}
```
