### ISSUE TITLE
Error while yarn installation.

### ISSUE THREAD

**Issue by ishaileshmishra** [vuestorefront/vue-storefront#5112]
Below is the log that might help to understand the issue.

```
shaileshmishra@Shaileshs-MacBook-Pro Documents % cd vue-storefront 
shaileshmishra@Shaileshs-MacBook-Pro vue-storefront % yarn installer
yarn run v1.22.10
$ node ./core/scripts/installer
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'semver/functions/inc'
Require stack:
- /Users/shaileshmishra/Documents/vue-storefront/packages/cli/themeTasks.js
- /Users/shaileshmishra/Documents/vue-storefront/core/scripts/installer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/shaileshmishra/Documents/vue-storefront/packages/cli/themeTasks.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shaileshmishra/Documents/vue-storefront/packages/cli/themeTasks.js',
    '/Users/shaileshmishra/Documents/vue-storefront/core/scripts/installer.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
shaileshmishra@Shaileshs-MacBook-Pro vue-storefront % 

```

**Comment by TamTran72111** [comment]
According the the [installation guidleline](https://docs.vuestorefront.io/guide/installation/linux-mac.html), I think you need to run `yarn` to install required packages first, then run `yarn installer` to run a script from those installed packages to setup and install extract things.

**Comment by ishaileshmishra** [comment]
Thanks @TamTran72111 Above was helpful.
