### ISSUE TITLE
issues running vsf init:theme local dev any help

### ISSUE THREAD

**Issue by awacris** [vuestorefront/vue-storefront#5306]
## Current behavior
   Configuring Vue Storefront theme
(node:6024) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: cd . && yarn cache clean && yarn
spawn cd ENOENT
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning url-loader@1.1.2: Invalid bin field for "url-loader".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-node@>=7.0.0".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-promise@>=4.0.0".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-standard@>=4.0.0".
error C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\core\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\core\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\T450s\\Desktop\\Project Folders\\Ecommerce\\vue-storefront\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\T450s\AppData\Local\Programs\Python\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\T450s\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\T450s\\Desktop\\Project Folders\\Ecommerce\\vue-storefront\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\T450s\Desktop\Project Folders\Ecommerce\vue-storefront\core\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
yarn cache v1.22.5
success Cleared cache.
Done in 17.59s.
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at notFoundError (C:\Users\T450s\AppData\Roaming\npm\node_modules\@vue-storefront\cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\T450s\AppData\Roaming\npm\node_modules\@vue-storefront\cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\T450s\AppData\Roaming\npm\node_modules\@vue-storefront\cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by awacris** [comment]
any one facing same issue update yarn.lock file change the node-sass version to match your node version. Sorry this is not a bug
