### ISSUE TITLE
Adding composition api to the VSF 1.12

### ISSUE THREAD

**Issue by tomisicm** [vuestorefront/vue-storefront#5604]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

Does vsf 1.12 can use composition-api? If so, how do we register it?
Its throwing Vue.use 
So far I've tried registering it on multiple places, but none of them work. Error is thrown when I access the component which uses compostion api.

Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
    at assert (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:45:15)
    at getVueConstructor (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:115:9)
    at isComponentInstance (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:234:15)
    at setupAccessControl (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:504:9)
    at reactive (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:683:5)
    at ref (/home/maki/work/paperchase/vsf/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:394:17)
    at Module../src/themes/paperchaseV2/hooks/Trustpilot.ts (src/themes/paperchaseV2/hooks/Trustpilot.ts:5:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/themes/paperchaseV2/components/molecules/m-trustpilot-footer.vue?vue&type=script&lang=js& (server-bundle.js:43687:80)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/themes/paperchaseV2/components/molecules/m-trustpilot-footer.vue?vue&type=script&lang=js& (src/themes/paperchaseV2/components/molecules/m-trustpilot-footer.vue?6957:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/themes/paperchaseV2/components/molecules/m-trustpilot-footer.vue (src/themes/paperchaseV2/components/molecules/m-trustpilot-footer.vue:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/themes/paperchaseV2/components/organisms/o-footer.vue?vue&type=script&lang=js& (server-bundle.js:43924:104)
    at __webpack_require__ (webpack/bootstrap:25:0)
    
  Composition API works if it is imported in every hook, but I'd prefer to avoid this approach,  is there another way?

**Comment by Fifciu** [comment]
We are not going to implement Composition API in VSF1. If you want to benefit from modern architecture, please use VSF2 which has been created for that.
