### ISSUE TITLE
Installation Issues with Boiler Plate Template

### ISSUE THREAD

**Issue by wpoosanguansit** [vuestorefront/vue-storefront#6180]
## Current behavior

The project structure created with cli and boiler plate template is broken and not usable when created.

## Expected behavior

Should create the proper folder structure like described in the doc and run and serve the pages successfully.

## Steps to reproduce the issue

I have installed VSF2 following the doc using cli:

npx @vue-storefront/cli init

and i chose integration Custom template from Github which i cloned from https://github.com/vuestorefront/ecommerce-integration-boilerplate

? What's your project name? storefront1
? Choose integration Custom template from Github
? Provide integration repository git link via https: https://github.com/wpoosanguansit/depatched.git
Cloning into '/Users/watt/Documents/Projects/Nuxt/storefront1'...
✔ VSF Project template initialized successfully.                                                                                      08:41:20
ℹ VSF Check out https://docs.vuestorefront.io/v2   

the process succeed with a number of warnings

[5/5] 🔨  Building fresh packages...
✨  Done in 64.95s.

![image](https://user-images.githubusercontent.com/90733/129062020-5af9326c-e130-47ae-a84f-bf191b3bd9d4.png)

But the project created does not seem to create the structure with folder like explained in the doc.

When run with yarn dev:

[dev:theme]  FATAL  Cannot find module '@vue-storefront/boilerplate-api/server'
[dev:theme] Require stack:
[dev:theme] - .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/lib/index.cjs.js
[dev:theme] - .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/nuxt/index.js
[dev:theme] - .../Documents/Projects/Nuxt/storefront1/node_modules/@nuxt/core/dist/core.js
[dev:theme] 
[dev:theme]   Require stack:
[dev:theme]   - .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/lib/index.cjs.js
[dev:theme]   - .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/nuxt/index.js
[dev:theme]   - .../Documents/Projects/Nuxt/storefront1/node_modules/@nuxt/core/dist/core.js
[dev:theme]   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[dev:theme]   at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[dev:theme]   at Module.require (internal/modules/cjs/loader.js:974:19)
[dev:theme]   at n (.../Documents/Projects/Nuxt/storefront1/node_modules/jiti/dist/v8cache.js:2:2472)
[dev:theme]   at .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/lib/index.cjs.js:99:25
[dev:theme]   at Array.reduce (<anonymous>)
[dev:theme]   at registerIntegrations (.../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/lib/index.cjs.js:94:41)
[dev:theme]   at createServer (.../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/lib/index.cjs.js:127:24)
[dev:theme]   at ModuleContainer.VueStorefrontMiddleware (.../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storefront/middleware/nuxt/index.js:5:19)
[dev:theme]   at ModuleContainer.addModule (.../Documents/Projects/Nuxt/storefront1/node_modules/@nuxt/core/dist/core.js:239:34)
[dev:theme] 
[dev:theme] 
[dev:theme] ╭──────────────────────────────────────────────────────────────────────────────╮│                                                                              ││   ✖ Nuxt Fatal Error                                                         ││                                                                              ││   Error: Cannot find module '@vue-storefront/boilerplate-api/server'         ││   Require stack:                                                             ││   -                                                                          ││   .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storef   ││   ront/middleware/lib/index.cjs.js                                           ││   -                                                                          ││   .../Documents/Projects/Nuxt/storefront1/node_modules/@vue-storef   ││   ront/middleware/nuxt/index.js                                              ││   -                                                                          ││   .../Documents/Projects/Nuxt/storefront1/node_modules/@nuxt/core/   ││   dist/core.js                                                               ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
[dev:theme] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[dev:theme] yarn run dev:theme exited with code 1
[dev:api-client] (!) Generated empty chunks
[dev:api-client] index, index
[dev:api-client] created lib/index.cjs.js, lib/index.es.js in 1.2s
[dev:api-client] bundles src/index.server.ts → server/index.js...
[dev:composables] [!] (plugin rpt2) Error: .../Documents/Projects/Nuxt/storefront1/packages/composables/src/useCart/index.ts(11,8): semantic error TS2307: Cannot find module '@vue-storefront/boilerplate-api' or its corresponding type declarations.
[dev:composables] src/useCart/index.ts
[dev:composables] Error: .../Documents/Projects/Nuxt/storefront1/packages/composables/src/useCart/index.ts(11,8): semantic error TS2307: Cannot find module '@vue-storefront/boilerplate-api' or its corresponding type declarations.

## Version of Vue Storefront

- [ ] Vue Storefront
- [x ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
Brave V1.27.111 (Aug 5, 2021) and Safari on Mac Big Sur
- OS: 
Mac Big Sur
- Node: 
v14.17.3
- Code Version: 
Version: 1.59.0

**Comment by jaydubb12** [comment]
@wpoosanguansit your error denotes that the build process cannot locate the api-client package. Did you happen to build the package(s) prior to running the dev theme? 

Here it is noting that it cannot find the "boilerplate-api" in useCart. My guess is that even though it is declared, that the issue is how the import resolutions are being managed. I have run into this A LOT with this project and have been working on a massive update I plan to submit that has refactored the build processes via rollup AND refactored the import features to get rid of all of the issues with the import resolution...as there are specific nuances with how you need to setup tsconfig AND eslint so that developers can leverage those features inherently to avoid issues in their IDE.

RECOMMENDATION
1. Install these packages...
 "eslint-plugin-import": "^2.24.0",
 "eslint-import-resolver-custom-alias": "^1.2.0",

2. Append the following to "extends" section of eslint to include...
```
""plugin:import/recommended",
"plugin:import/typescript",
```
3. Append the following to "plugins" section of eslint to include...
```
"plugins": [
    "@typescript-eslint",
    "import",
  ],
```

4. Update your other sections with the following configs...
```
 "parser": "vue-eslint-parser",
  "parserOptions": {
    "parser": "@typescript-eslint/parser",
    "sourceType": "module",
    "project": [
      "./tsconfig.json"
    ],
    "extraFileExtensions": [".vue"],
    "vueFeatures": {
      "filter": true, //If you specify false, the parser does not parse | as a filter, and is parsed similar to vue3
      "interpolationAsNonHTML": false, //when = true, will be parsed as Vue3
      "styleCSSVariableInjection": true
    }
  },
  "settings": {
    "import/extensions": [
      //A list of file extensions that will be parsed as modules and inspected for exports.
      ".js",
      ".jsx",
      ".ts",
      ".tsx",
      ".vue",
      ".mjs",
      ".jsx"
    ],
    "import/resolver": {
      "eslint-import-resolver-custom-alias": {
        "alias": {
          "@": "./", // sets the import resolver to match what tsconfig uses...and note that @ is needed to support various vue features
          "~": "./", // can help with internal resolution...an alternative can be ~./node_modules
          "@atoms": "./src/components/atoms",
          "@molecules": "./src/components/molecules",
          "@organisms": "./src/components/organisms",
          "@css": "./src/css"
        },
        "extensions": [
          ".js",
          ".jsx",
          ".vue",
          ".ts",
          ".tsx",
          ".json"
        ],
        "packages": [
          "packages/vue",
          "packages/shared",
          "packages/nuxt"
        ]
      },
      "node": {
        "extensions": [
          ".js",
          ".jsx",
          ".ts",
          ".tsx",
          ".vue",
          ".json",
          ".mjs"
        ],
        "moduleDirectory": [
          "node_modules",
          "packages/core",
          "packages/boilerplate"
        ]
      },

5. Here is my corresponding tsconfig...and NOTE that I have worked to upgrade EVERYTHING here from es5 / es2015 to es6...so you may want to consider that before copying and pasting in
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "../tsconfig.base.json",
  "include": ["src"],
  "exclude": ["node_modules", "lib"],
  "compilerOptions": {
      "allowUnreachableCode": false,
      "outDir": "./lib",
      "esModuleInterop": true,
      "target": "es6",
      "module": "es6",
      "moduleResolution": "node",
      "importHelpers": true,
      "noEmitHelpers": true,
      "sourceMap": true,
      "declaration": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true,
      "baseUrl": "./",
      "preserveSymlinks": true,
  },

}
```
