### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by soojy** [vuestorefront/vue-storefront#6734]
### I try to use vendure with vsf

```

 ERROR  [VSF][error]:  [Network error]: TypeError: Only absolute URLs are supported                                                                                             02:29:09  


 ERROR  [VSF][error]:  useUser/load Request failed with status code 500                                                                                                         02:29:09  

  at createError (node_modules\axios\lib\core\createError.js:16:15)
  at settle (node_modules\axios\lib\core\settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:260:11)
  at IncomingMessage.emit (node:events:402:35)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [VSF][error]:  [Network error]: TypeError: Only absolute URLs are supported                                                                                             02:29:09  


 ERROR  [VSF][error]:  useCart/load Request failed with status code 500                                                                                                         02:29:09  

  at createError (node_modules\axios\lib\core\createError.js:16:15)
  at settle (node_modules\axios\lib\core\settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:260:11)
  at IncomingMessage.emit (node:events:402:35)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [VSF][error]:  [Network error]: TypeError: Only absolute URLs are supported                                                                                             02:29:09  


 ERROR  [VSF][error]:  useCategory/undefined/search Request failed with status code 500                                                                                         02:29:09  

  at createError (node_modules\axios\lib\core\createError.js:16:15)
  at settle (node_modules\axios\lib\core\settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:260:11)
  at IncomingMessage.emit (node:events:402:35)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'map')"                                                                           02:29:09  

found in

---> <SfHeader> at node_modules/@storefront-ui/vue/src/components/organisms/SfHeader/SfHeader.vue
       <AppHeader> at components/AppHeader.vue
         <Anonymous>
           <LazyHydrate>
             <DefaultLayout> at layouts/default.vue
               <Root>


```

### What version of Vue Storefront are you using?

2.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi @soojy, which e-commerce integration are you using?

**Comment by getwebM** [comment]
How do you solve this problem? I have the same error.

**Comment by nkamuo** [comment]
I also have this issue. Does anybody have a solution.
