### ISSUE TITLE
[Bug]: Test store using Commerce Tools is broken from the start

### ISSUE THREAD

**Issue by justageek** [vuestorefront/vue-storefront#6737]
### Describe the Bug

Just trying to load Vue Storefront UI I get the following, actually just trying to build the store with npm run dev produces
```
[VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  useUser/load Request failed with status code 500                                                                                                                                      16:10:43

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (node:events:377:35)
  at endReadableNT (node:internal/streams/readable:1312:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [VSF][error]:  useCart/load Request failed with status code 500                                                                                                                                      16:10:44

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (node:events:377:35)
  at endReadableNT (node:internal/streams/readable:1312:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
 My middleware and api token have the following scopes:
```
scopes: [
            'create_anonymous_token:core-commerce-store',
            'view_categories:core-commerce-store',
            'view_published_products:core-commerce-store',
            'view_stores:core-commerce-store',
            'manage_my_profile:core-commerce-store',
            'manage_my_orders:core-commerce-store',
            'manage_my_payments:core-commerce-store',
            'manage_my_shopping_lists:core-commerce-store'
          ]
```

### Expected behavior

I would expect to be able to load the home page of the store without error.

### What version of Vue Storefront are you using?

 "@vue-storefront/nuxt": "~2.5.3",

### What version of Node.js are you using?

1`6.0.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Relevant log output

```shell
[VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  [Network error]: BadRequest: Permissions exceeded. Only the following permissions can be requested: manage_my_shopping_lists, manage_my_orders, create_anonymous_token, manage_my_payments, view_categories, view_published_products, manage_my_profile


 ERROR  [VSF][error]:  useUser/load Request failed with status code 500                                                                                                                                      16:10:43

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (node:events:377:35)
  at endReadableNT (node:internal/streams/readable:1312:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [VSF][error]:  useCart/load Request failed with status code 500                                                                                                                                      16:10:44

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (node:events:377:35)
  at endReadableNT (node:internal/streams/readable:1312:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
```


### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
We no longer support open-source version of the commercetools integration. If you want to access to actively maintained Enterprise version, [reach out to our Sales team](https://www.vuestorefront.io/contact/sales).
