### ISSUE TITLE
[Bug]: Default Invalidation Handler does not work correctly

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/vue-storefront#6884]
### Describe the Bug

We used redis cache driver, and caching is working very well. 

When I call the invalidation URL I get error (default invalidation handler):
```
[dev:theme]  ERROR  [VSF][error]:  Cache driver thrown an error when invalidating cache! Operation skipped.

[dev:theme]  ERROR  [VSF][error]:  response.status is not a function

[dev:theme]   at handler (/Users/Documents/projects/binshops/vuestorefront/prestashop/node_modules/@vue-storefront/cache/nuxt/index.js:32:7)

[dev:theme]  ERROR  response.status is not a function

[dev:theme]   at handler (/Users/Documents/projects/binshops/vuestorefront/prestashop/node_modules/@vue-storefront/cache/nuxt/index.js:39:7)
```
My cache config:
```
    ['@vue-storefront/cache/nuxt', {
      enabled: true,
      invalidation: {
        endpoint: '/cache-invalidate',
        key: 'uniqueKey',
        handlers: [
          '@vue-storefront/cache/defaultHandler'
        ]
      },
      driver: [
        '@vue-storefront/redis-cache',
        {
          defaultTimeout: 86400,
          redis: {
            host: 'localhost',
            port: 6379
          }
        }
      ]
    }]
```

I use this url to clear redis:
http://localhost:3000/cache-invalidate?key=uniqueKey&amp;tags=*

followed this article:
http://localhost:3000/cache-invalidate?key=uniqueKey&amp;tags=*

### Expected behavior

cache should be cleared after calling this url. 

### What version of Vue Storefront are you using?

any

### What version of Node.js are you using?

any

### What browser (and version) are you using?

any

### What operating system (and version) are you using?

any

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
two people reported on discord with same error on discord:
https://discord.com/channels/770285988244750366/770285988244750370/1068531011668938752

https://discord.com/channels/770285988244750366/770285988244750370/1023931660774932500

**Comment by jeffpdotone** [comment]
Our team suggests doing the following.

Add the file below with the content.

# plugins/body-parser.js

```typescript
const bodyParser = require('body-parser')
const app = require('express')()

app.use(bodyParser.json())
module. Exports = app
```

Remember to add them in your nuxt.config.js

**Comment by samberrry** [comment]
Hey @jeffpdotone ,
first I tried it with `body-parser.js` and `yarn build` ran with error. I thought the problem is that it should be bound to server-side only, so I changed it to `body-parser.server.js`. Code built and ran successfully, however still same error.

```
[dev:theme]  ERROR  [VSF][error]:  Cache driver thrown an error when invalidating cache! Operation skipped.
[dev:theme] 
[dev:theme] 
[dev:theme]  ERROR  [VSF][error]:  response.status is not a function
[dev:theme] 
[dev:theme]   at handler (/Users/Documents/projects/binshops/vuestorefront/prestashop/node_modules/@vue-storefront/cache/nuxt/index.js:32:7)
[dev:theme] 
[dev:theme] 
[dev:theme]  ERROR  response.status is not a function
[dev:theme] 
[dev:theme]   at handler (/Users/Documents/projects/binshops/vuestorefront/prestashop/node_modules/@vue-storefront/cache/nuxt/index.js:39:7)
[dev:theme] 
```

thanks

**Comment by samberrry** [comment]
```
  plugins: [
    '~/plugins/body-parser.server.js'
  ],
```

**Comment by samberrry** [comment]
content:
```
const bodyParserServer = require('body-parser');
const app = require('express')();

app.use(bodyParserServer.json());
module.exports = app;

```

**Comment by odranoelBR** [comment]
Same problem here using node v14 LTS.
We used the library whitout this problem for a long time and didn't have the problem.

Checking node HTTP Response object, the versions 12 14 16 don't have the method .status
https://nodejs.org/docs/latest-v14.x/api/http.html

Very strange, probaly have a plugins or something wrapping the object.

**Comment by odranoelBR** [comment]
I added the bodyparse on the middleware without errors, but still not solve the .status problem.
![Screenshot from 2023-02-28 18-37-02](https://user-images.githubusercontent.com/7774534/221986407-5e50e20c-492f-442d-8712-d7eae4d58e9b.png)

**Comment by odranoelBR** [comment]
@samberrry Solved addyng the body parser to server middleware.
![Screenshot from 2023-02-28 18-53-45](https://user-images.githubusercontent.com/7774534/221990019-e2835bba-e90b-41ff-8db4-ac0fc2ecc4e0.png)

The invalidation cache endpoint works!

**Comment by samberrry** [comment]
many thanks @odranoelBR , I will try it and I will update here, hope it solves the issue.

**Comment by tbanys** [comment]
works for me to. Thanks @odranoelBR

**Comment by skirianov** [comment]
@samberrry let me add our TL, let's see what they think. @WojtekTheWebDev any ideas what would be the best solution here?

**Comment by matthijsch** [comment]
With the body-parser code loaded by serverMiddleware I receive the following error:

```
response.js:43 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
```
this is concerning the line "var res = Object.create(http.ServerResponse.prototype)"

Does anyone have a solution for this?
